name: test
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          #- ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python 3.8.15
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.15

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute Behave tests
        run: |
          # Replace with the actual command to run your Behave tests
          behave

      - name: Upload Test Results
        if: always()  # Upload results even if the previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: Test Data/Report.xml
