name: Release_Pipeline_All_OS
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Execute Behave tests - Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd features
          behave OrgangeHRMLogin.feature
      - name: Execute Behave tests - MacOS
        if: matrix.os == 'macos-latest'
        run: |
          behave ./features/OrgangeHRMLogin.feature
      # - name: Execute Behave tests - Ubuntu
      #   if: matrix.os == 'ubuntu-latest'
      #   run: |
      #     behave ./features/OrgangeHRMLogin.feature
