name: test
'on':
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *
jobs:
  build:
    strategy:
      matrix:
        os:
          - windows-latest
          - macos-latest
          #- ubuntu-latest
    runs-on: '${{ matrix.os }}'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.8.15
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.2
      - name: Install dependencies
        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt
      - name: Execute Behave tests
        run: |
          feature/OrangeHRMLogin.py
          behave
      - name: Upload Test Results
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: Test Data/Report.xml
